# Generated by Django 2.2.5 on 2021-03-10 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210311_0048'),
    ]

    operations = [
    ]
